---
- name: "unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: "executing node"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start npm -- start
    pm2 ls
  register: execute_node_server

- name: print message
  debug:
    msg: "{{ execute_node_server.stdout_lines }}"